export let tableAuthors = [
  {
    img: require("../Assets/img/Tables/team-2.png"),
    name: "Michael John",
    email: "michael@mail.com",
    jobTitle: "Manager",
    jobName: "Organization",
    isOnline: true,
    joined: "23/04/18",
  },
  {
    img: require("../Assets/img/Tables/avatar.png"),
    name: "Alexa Liras",
    email: "alexa@mail.com",
    jobTitle: "Programmer",
    jobName: "Developer",
    isOnline: false,
    joined: "23/12/20",
  },
  {
    img: require("../Assets/img/Tables/avatar (1).png"),
    name: "Laure Perrier",
    email: "laure@mail.com",
    jobTitle: "Executive",
    jobName: "Projects",
    isOnline: true,
    joined: "13/04/19",
  },
  {
    img: require("../Assets/img/Tables/ivana-square.png"),
    name: "Miriam Eric",
    email: "miriam@mail.com",
    jobTitle: "Marketing",
    jobName: "Organization",
    isOnline: true,
    joined: "03/04/21",
  },
  {
    img: require("../Assets/img/Tables/team-2.png"),
    name: "Richard Gran",
    email: "richard@mail.com",
    jobTitle: "Manager",
    jobName: "Organization",
    isOnline: false,
    joined: "23/03/20",
  },
  {
    img: require("../Assets/img/Tables/avatar (2).png"),
    name: "John Levi",
    email: "john@mail.com",
    jobTitle: "Tester",
    jobName: "Developer",
    isOnline: false,
    joined: "14/04/17",
  },
];
